version: "3.1"

services:
  redis:
    image: redis:3.2-alpine

  python:
    build: .docker/python/
    volumes:
    - .:/app
    - .venv/.cache:/.cache
    working_dir: /app
    depends_on:
    - redis
    environment:
      # @link https://pipenv.readthedocs.io/en/latest/install/#virtualenv-mapping-caveat
      PIPENV_VENV_IN_PROJECT: 1
