version: "3"

services:
  rails:
    build: ./.docker/rails
    volumes:
      - .:/app
      - ./.docker/shared/.bundle/:/usr/local/bundle
      - ./.docker/shared/.yarn/:/.cache/yarn
    working_dir: /app
    ports:
      - 3000:3000
      - 3005:3005
    depends_on:
      - postgres
    env_file:
      - .local.dev.env

  postgres:
    image: postgres:10-alpine
    ports:
      - 5433:5432
    env_file:
      - .local.dev.env
