version: "3.1"

services:
  db:
    image: postgres:10-alpine
    ports:
      - 5433:5432
    env_file:
      - .env

  python: &python
    build: .docker/python/
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db
    environment:
      # @link https://github.com/pypa/pipenv/blob/master/docs/advanced.rst#-custom-virtual-environment-location
      WORKON_HOME: /app/pipenv

      POSTGRES_HOST: db
