version: "3"

services:

  postgres:
    image: postgres:10-alpine
    ports:
    - 5433:5432
    env_file:
    - .dev.env

  python:
    build: ./.docker/python
    volumes:
    - .:/app
    - ./.cache:/.cache
    - ./.cache/.pylint.d:/.pylint.d
    - ./.docker/python/venv-shell.sh:/venv-shell.sh:ro
    working_dir: /app
    env_file:
    - .dev.env
    environment:
      DJANGO_SETTINGS_MODULE: project.settings.dev
    depends_on:
    - postgres
