[tool.poetry]
name = "goodauldbooks-django"
version = "0.1.0"
description = ""
authors = ["Olivier Philippon <olivier@rougemine.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^2.1"
psycopg2 = "^2.7"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]
black = "=18.9b0"
pylint = "^2.2"
coloredlogs = "^10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
