version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_DB: goodauldbooks
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8083:8080